function model=readYAMLmodel(fileName, verbose)
% readYAMLmodel
%   Reads a model from a YAML file.
%
%   Two YAML layouts are recognised and handled automatically:
%   1. The cobrapy-style layout that writeYAMLmodel produces since
%      RAVEN 2.12.0, fully compatible with cobrapy.
%   2. The older layout generated by RAVEN before 2.12.0.
%   The main visual difference is that the older layout starts with
%   --- followed by !!omap. The older layout can still be read, but
%   writeYAMLmodel will only write the new cobrapy-style layout
%   since RAVEN 2.12.0.
%   In both cases the function returns a regular RAVEN model struct.
%
%   Input:
%   fileName    path to the YAML file. If empty, a dialog window opens
%               so the user can pick the file.
%   verbose     if true, print progress messages while reading
%               (optional, default false).
%
%   Output:
%   model       a RAVEN model structure.
%
% Usage: model = readYAMLmodel(fileName, verbose)
if nargin<1 || isempty(fileName)
    [fileName, pathName] = uigetfile({'*.yml;*.yaml'}, 'Please select the model file');
    if fileName == 0
        error('You should select a model file')
    else
        fileName = fullfile(pathName,fileName);
    end
end
if nargin < 2
    verbose = false;
end

if ~isfile(fileName)
    error('Yaml file %s cannot be found', string(fileName));
end

if verLessThan('matlab','9.9') %readlines introduced 2020b
    fid=fopen(fileName);
    line_raw=cell(1000000,1);
    i=1;
    while ~feof(fid)
        line_raw{i}=fgetl(fid);
        i=i+1;
    end
    line_raw(i:end)=[];
    line_raw=string(line_raw);
    fclose(fid);
else
    line_raw=readlines(fileName);
end

% Pick which parser to use. The older RAVEN files start with `---`
% and use `!!omap` tags; the newer cobrapy-style files do not.
if isLegacyFormat(line_raw)
    model = parseYAMLLegacy(line_raw, verbose);
else
    model = parseCanonical(line_raw, verbose);
end
end

% --- Format detection ---------------------------------------------------

function tf = isLegacyFormat(line_raw)
tf = false;
for k = 1:min(numel(line_raw), 50)
    s = strtrim(char(line_raw{k}));
    if isempty(s)
        continue
    end
    if strcmp(s,'---') || strcmp(s,'!!omap') || contains(s,'!!omap')
        tf = true;
        return
    end
    % First non-empty, non-comment line that's neither `---` nor `!!omap`
    % means we're in canonical land.
    if s(1) ~= '#'
        return
    end
end
end

% --- Canonical-format parser -------------------------------------------

function model = parseCanonical(line_raw, verbose)
%Parser for the cobrapy-style YAML layout. The file is read into a
%nested struct/cell tree first, then translated into a standard RAVEN
%model struct.

if verbose
    fprintf('Parsing YAML (cobrapy layout)...\n');
end

%Strip blank lines and full-line comments so the parser only sees real
%content. We keep the line index 1-based.
lines = string(line_raw);
keep  = ~arrayfun(@(s) isempty(strtrim(char(s))) || startsWith(strtrim(char(s)),'#'), lines);
lines = lines(keep);

[doc, ~] = parseMapping(cellstr(lines), 1, 0);

model = canonicalToModel(doc, verbose);
end

function [out, idx] = parseMapping(lines, idx, baseIndent)
%Parse a YAML mapping whose keys live at column == baseIndent. Returns
%an Nx2 cell `{key, value; ...}` (verbatim YAML keys, no escaping).
out = cell(0, 2);
while idx <= numel(lines)
    raw = lines{idx};
    [indent, content] = splitIndent(raw);
    if indent < baseIndent
        return
    end
    if indent > baseIndent
        %Defensive: a mapping line at unexpected indent. Skip it.
        idx = idx + 1;
        continue
    end
    if startsWith(content,'-')
        %A list under a mapping key would have been consumed by the parent
        %call when it saw `key:` with no inline value. Reaching `-` here
        %means we've stepped outside the mapping; return.
        return
    end
    [key, value, hasInline] = splitKeyValue(content);
    if isempty(key)
        idx = idx + 1;
        continue
    end
    if hasInline
        out(end+1, :) = {key, parseScalar(value)}; %#ok<AGROW>
        idx = idx + 1;
    else
        %Look ahead at the value block. Cases:
        %  next line indent > baseIndent, starts with `-` => nested list
        %  next line indent > baseIndent, no `-` => nested mapping
        %  next line indent == baseIndent, starts with `-` => "compact"
        %      list (YAML lets a list share indent with its parent key,
        %      the standard cobra-style annotation idiom)
        %  anything else => empty value
        nextIdx = idx + 1;
        if nextIdx > numel(lines)
            out(end+1, :) = {key, ''}; %#ok<AGROW>
            return
        end
        [nIndent, nContent] = splitIndent(lines{nextIdx});
        if nIndent == baseIndent && startsWith(nContent,'-')
            [child, idx] = parseList(lines, nextIdx, baseIndent);
            out(end+1, :) = {key, child}; %#ok<AGROW>
        elseif nIndent > baseIndent
            if startsWith(nContent,'-')
                [child, idx] = parseList(lines, nextIdx, nIndent);
            else
                [child, idx] = parseMapping(lines, nextIdx, nIndent);
            end
            out(end+1, :) = {key, child}; %#ok<AGROW>
        else
            out(end+1, :) = {key, ''}; %#ok<AGROW>
            idx = nextIdx;
        end
    end
end
end

function [out, idx] = parseList(lines, idx, baseIndent)
%Parse a YAML list whose `-` markers live at column == baseIndent.
out = {};
while idx <= numel(lines)
    raw = lines{idx};
    [indent, content] = splitIndent(raw);
    if indent < baseIndent
        return
    end
    if indent > baseIndent
        idx = idx + 1;
        continue
    end
    if ~startsWith(content,'-')
        return
    end
    %Strip the `- ` marker, leaving either a scalar or the first
    %key/value of a mapping element.
    after = regexprep(content,'^-\s*','');
    if isempty(after)
        %Item is a bare `-` followed by a nested mapping on the next line.
        nextIdx = idx + 1;
        if nextIdx > numel(lines)
            out{end+1,1} = ''; %#ok<AGROW>
            return
        end
        [nIndent, nContent] = splitIndent(lines{nextIdx});
        if startsWith(nContent,'-')
            [child, idx] = parseList(lines, nextIdx, nIndent);
        else
            [child, idx] = parseMapping(lines, nextIdx, nIndent);
        end
        out{end+1,1} = child; %#ok<AGROW>
    else
        [key, value, hasInline] = splitKeyValue(after);
        if isempty(key)
            %Scalar list item, e.g. `- foo`.
            out{end+1,1} = parseScalar(after); %#ok<AGROW>
            idx = idx + 1;
        else
            %The element is a mapping; its first key sits inline with the
            %`-`. Capture that first key (either as an inline scalar, or
            %as a nested block when the value comes on the following
            %lines), then run the continuation loop to pick up any
            %remaining keys of the same element.
            element = cell(0, 2);
            if hasInline
                element(end+1, :) = {key, parseScalar(value)}; %#ok<AGROW>
                idx = idx + 1;
            else
                nextIdx = idx + 1;
                if nextIdx > numel(lines)
                    element(end+1, :) = {key, ''}; %#ok<AGROW>
                    idx = nextIdx;
                else
                    [nIndent, nContent] = splitIndent(lines{nextIdx});
                    if nIndent <= baseIndent + 1
                        %No nested block; key has an empty value.
                        element(end+1, :) = {key, ''}; %#ok<AGROW>
                        idx = nextIdx;
                    else
                        if startsWith(nContent,'-')
                            [grand, idx] = parseList(lines, nextIdx, nIndent);
                        else
                            [grand, idx] = parseMapping(lines, nextIdx, nIndent);
                        end
                        element(end+1, :) = {key, grand}; %#ok<AGROW>
                    end
                end
            end
            %Continuation: subsequent lines indented at (baseIndent + 2)
            %belong to this same element (its remaining keys).
            while idx <= numel(lines)
                raw2 = lines{idx};
                [i2, c2] = splitIndent(raw2);
                if i2 < baseIndent + 2
                    break
                end
                if i2 > baseIndent + 2
                    idx = idx + 1;
                    continue
                end
                if startsWith(c2,'-')
                    %Reached the next list element belonging to a parent
                    %list (e.g. annotation values). Stop here.
                    break
                end
                [k2, v2, has2] = splitKeyValue(c2);
                if isempty(k2)
                    idx = idx + 1;
                    continue
                end
                if has2
                    element(end+1, :) = {k2, parseScalar(v2)}; %#ok<AGROW>
                    idx = idx + 1;
                else
                    nxt = idx + 1;
                    if nxt > numel(lines)
                        element(end+1, :) = {k2, ''}; %#ok<AGROW>
                        idx = nxt;
                        break
                    end
                    [ni, nc] = splitIndent(lines{nxt});
                    if ni <= i2
                        element(end+1, :) = {k2, ''}; %#ok<AGROW>
                        idx = nxt;
                        continue
                    end
                    if startsWith(nc,'-')
                        [grand, idx] = parseList(lines, nxt, ni);
                    else
                        [grand, idx] = parseMapping(lines, nxt, ni);
                    end
                    element(end+1, :) = {k2, grand}; %#ok<AGROW>
                end
            end
            out{end+1,1} = element; %#ok<AGROW>
        end
    end
end
end

function [indent, content] = splitIndent(line)
line = char(line);
n = numel(line);
i = 1;
while i <= n && line(i) == ' '
    i = i + 1;
end
indent = i - 1;
content = line(i:end);
end

function [key, value, hasInline] = splitKeyValue(content)
%Detect `key: value` (hasInline=true), `key:` (hasInline=false), or no key
%(returns empty key). A `:` inside a quoted string is not a separator.
key = '';
value = '';
hasInline = false;
content = char(content);
if isempty(content)
    return
end
%Find the first colon that's not inside quotes.
inQuote = false;
colonPos = 0;
for k = 1:numel(content)
    c = content(k);
    if c == '"'
        inQuote = ~inQuote;
    elseif c == ':' && ~inQuote
        colonPos = k;
        break
    end
end
if colonPos == 0
    return
end
key = strtrim(content(1:colonPos-1));
rest = strtrim(content(colonPos+1:end));
if isempty(rest)
    hasInline = false;
else
    hasInline = true;
    value = rest;
end
end

function v = parseScalar(s)
s = strtrim(char(s));
if isempty(s)
    v = '';
    return
end
%Strip an inline `# ...` comment (only when `#` is preceded by whitespace
%and we're not inside a quoted string).
if s(1) ~= '"' && s(1) ~= ''''
    commentStart = regexp(s,'\s#','once');
    if ~isempty(commentStart)
        s = strtrim(s(1:commentStart));
    end
end
%Strip surrounding quotes (either ".." or '..'). YAML uses both, and
%cobrapy/geckopy emit single quotes for empty strings via PyYAML.
if numel(s) >= 2 && ((s(1) == '"' && s(end) == '"') || (s(1) == '''' && s(end) == ''''))
    v = s(2:end-1);
    return
end
%Normalise YAML's `.nan`/`.NaN`/`nan` to the canonical 'NaN' literal so
%downstream str2double calls produce NaN.
if strcmpi(s,'.nan') || strcmpi(s,'nan')
    v = 'NaN';
    return
end
v = s;
end

function tf = mapHas(pairs, key)
%True if `pairs` (Nx2 cell {key, value; ...} from parseMapping) contains key.
tf = ~isempty(pairs) && any(strcmp(pairs(:,1), key));
end

function v = mapGet(pairs, key, default)
%Return the value for `key` in `pairs`, or `default` if absent.
if nargin < 3
    default = '';
end
if isempty(pairs)
    v = default;
    return
end
hit = find(strcmp(pairs(:,1), key), 1, 'first');
if isempty(hit)
    v = default;
else
    v = pairs{hit, 2};
end
end

function pairs = mapDelete(pairs, key)
%Remove the entry whose key equals `key`.
if isempty(pairs)
    return
end
keep = ~strcmp(pairs(:,1), key);
pairs = pairs(keep, :);
end

% --- Canonical YAML tree -> RAVEN model struct -------------------------

function model = canonicalToModel(doc, verbose)
%Translate the (cell{N,2}) pair tree produced by parseMapping into the
%standard RAVEN model struct, applying the same defaults and post-
%processing the legacy parser does.

modelFields = legacyYAMLmodelFields();
model = initYAMLmodel(modelFields);

%Top-level scalar fields. The cobrapy schema lifts id/name to the top
%level; legacy callers sometimes wrote `version` at the top too. metaData
%(if present) carries provenance and defaultLB/defaultUB.
model.id          = getField(doc, 'id', '');
model.name        = getField(doc, 'name', '');
model.version     = getField(doc, 'version', '');
model.description = getField(doc, 'description', '');

md = mapGet(doc, 'metaData', cell(0,2));
if iscell(md) && ~isempty(md)
    %id/name in metaData take a back seat to top-level values (canonical)
    %but are still accepted (forward compat with legacy on-disk leakage).
    if isempty(model.id);          model.id = getField(md, 'id', ''); end
    if isempty(model.id);          model.id = getField(md, 'short_name', ''); end
    if isempty(model.name);        model.name = getField(md, 'name', ''); end
    if isempty(model.description); model.description = getField(md, 'full_name', ''); end
    if isempty(model.version);     model.version = getField(md, 'version', ''); end
    model.date = getField(md, 'date', '');
    if mapHas(md, 'taxonomy');     model.annotation.taxonomy = getField(md, 'taxonomy', ''); end
    if mapHas(md, 'note');         model.annotation.note = getField(md, 'note', ''); end
    if mapHas(md, 'description');  model.annotation.note = getField(md, 'description', ''); end
    if mapHas(md, 'sourceUrl');    model.annotation.sourceUrl = getField(md, 'sourceUrl', ''); end
    if mapHas(md, 'github') && ~isfield(model.annotation, 'sourceUrl')
        model.annotation.sourceUrl = getField(md, 'github', '');
    end
    if mapHas(md, 'givenName');    model.annotation.givenName = getField(md, 'givenName', ''); end
    if mapHas(md, 'familyName');   model.annotation.familyName = getField(md, 'familyName', ''); end
    if mapHas(md, 'authors');      model.annotation.authorList = getField(md, 'authors', ''); end
    if mapHas(md, 'email');        model.annotation.email = getField(md, 'email', ''); end
    if mapHas(md, 'organization'); model.annotation.organization = getField(md, 'organization', ''); end
    if mapHas(md, 'defaultLB');    model.annotation.defaultLB = str2double(getField(md, 'defaultLB', 'NaN')); end
    if mapHas(md, 'defaultUB');    model.annotation.defaultUB = str2double(getField(md, 'defaultUB', 'NaN')); end
end

%Compartments (flat mapping `id -> name`).
comps = mapGet(doc, 'compartments', cell(0,2));
if iscell(comps) && ~isempty(comps)
    n = size(comps, 1);
    model.comps     = cell(n, 1);
    model.compNames = cell(n, 1);
    for k = 1:n
        model.comps{k,1}     = comps{k, 1};
        model.compNames{k,1} = stringify(comps{k, 2});
    end
end

%Metabolites. String-cell fields are seeded with '' so unset entries
%end up char-empty (matching the legacy pipeline), not [] empty-double.
%Numeric-cell fields (metCharges, metDeltaG) stay as cell(nm,1) so that
%after str2double their unset entries become NaN, which finaliseYAMLmodel
%treats as "all empty" and drops the field entirely.
mets = mapGet(doc, 'metabolites', {});
if iscell(mets) && size(mets, 2) ~= 2  % a list (Mx1), not a key/value map
    nm = numel(mets);
    model.mets        = repmat({''},nm,1);
    model.metNames    = repmat({''},nm,1);
    model.metComps    = repmat({''},nm,1);
    model.metFormulas = repmat({''},nm,1);
    model.metCharges  = cell(nm,1);
    model.inchis      = repmat({''},nm,1);
    model.metSmiles   = repmat({''},nm,1);
    model.metNotes    = repmat({''},nm,1);
    model.metFrom     = repmat({''},nm,1);
    model.metDeltaG   = cell(nm,1);
    model.metMiriams  = cell(nm,1);
    for k = 1:nm
        m = mets{k};
        if ~iscell(m) || size(m,2) ~= 2, continue, end
        model.mets{k}        = getField(m,'id','');
        model.metNames{k}    = getField(m,'name','');
        model.metComps{k}    = getField(m,'compartment','');
        model.metFormulas{k} = getField(m,'formula','');
        model.metCharges{k}  = getField(m,'charge','');
        model.inchis{k}      = getField(m,'inchis','');
        ann = mapGet(m, 'annotation', cell(0,2));
        if iscell(ann) && size(ann, 2) == 2
            if mapHas(ann, 'smiles')
                model.metSmiles{k} = collapseList(mapGet(ann, 'smiles'));
                ann = mapDelete(ann, 'smiles');
            end
            if mapHas(ann, 'notes')
                model.metNotes{k} = collapseList(mapGet(ann, 'notes'));
                ann = mapDelete(ann, 'notes');
            end
            if mapHas(ann, 'metFrom')
                model.metFrom{k} = collapseList(mapGet(ann, 'metFrom'));
                ann = mapDelete(ann, 'metFrom');
            end
            if mapHas(ann, 'deltaG')
                model.metDeltaG{k} = collapseList(mapGet(ann, 'deltaG'));
                ann = mapDelete(ann, 'deltaG');
            end
            model.metMiriams{k} = annotationToMiriam(ann);
        end
        %Legacy callers placed these as top-level keys; honour both:
        if isempty(model.metSmiles{k}) && mapHas(m, 'smiles')
            model.metSmiles{k} = getField(m, 'smiles', '');
        end
        if isempty(model.metNotes{k}) && mapHas(m, 'notes')
            model.metNotes{k} = getField(m, 'notes', '');
        end
        if isempty(model.metFrom{k}) && mapHas(m, 'metFrom')
            model.metFrom{k} = getField(m, 'metFrom', '');
        end
        if isempty(model.metDeltaG{k}) && mapHas(m, 'deltaG')
            model.metDeltaG{k} = getField(m, 'deltaG', '');
        end
    end
end

%Reactions.
equations = {};
rxns = mapGet(doc, 'reactions', {});
if iscell(rxns) && size(rxns, 2) ~= 2
    nr = numel(rxns);
    model.rxns                = repmat({''},nr,1);
    model.rxnNames            = repmat({''},nr,1);
    model.lb                  = cell(nr,1);
    model.ub                  = cell(nr,1);
    model.rev                 = cell(nr,1);
    model.grRules             = repmat({''},nr,1);
    model.eccodes             = repmat({''},nr,1);
    model.subSystems          = cell(nr,1);
    model.rxnReferences       = repmat({''},nr,1);
    model.rxnNotes            = repmat({''},nr,1);
    model.rxnFrom             = repmat({''},nr,1);
    model.rxnConfidenceScores = cell(nr,1);
    model.rxnDeltaG           = cell(nr,1);
    model.rxnMiriams          = cell(nr,1);
    model.c                   = zeros(nr,1);
    for k = 1:nr
        r = rxns{k};
        if ~iscell(r) || size(r,2) ~= 2, continue, end
        model.rxns{k}                = getField(r,'id','');
        model.rxnNames{k}            = getField(r,'name','');
        model.lb{k}                  = getField(r,'lower_bound','');
        model.ub{k}                  = getField(r,'upper_bound','');
        model.rev{k}                 = getField(r,'rev','');
        model.grRules{k}             = getField(r,'gene_reaction_rule','');
        model.rxnConfidenceScores{k} = getField(r,'confidence_score','');
        if mapHas(r, 'objective_coefficient')
            model.c(k) = str2double(getField(r, 'objective_coefficient', '0'));
        end
        %Stoich: flat mapping `metId -> coeff` (preserved as Nx2 pairs).
        stoich = mapGet(r, 'metabolites', cell(0,2));
        if iscell(stoich) && size(stoich, 2) == 2
            for s = 1:size(stoich, 1)
                metId = stoich{s, 1};
                coeff = str2double(stringify(stoich{s, 2}));
                equations(end+1,1:3) = {k, metId, coeff}; %#ok<AGROW>
            end
        end
        %Annotation block: ec-code, subsystem, references, notes, rxnFrom,
        %deltaG go to RAVEN's dedicated fields; everything else becomes
        %a miriam entry.
        ann = mapGet(r, 'annotation', cell(0,2));
        if iscell(ann) && size(ann, 2) == 2
            if mapHas(ann, 'ec-code')
                model.eccodes{k} = strjoin(toCellList(mapGet(ann, 'ec-code')), ';');
                ann = mapDelete(ann, 'ec-code');
            end
            if mapHas(ann, 'subsystem')
                model.subSystems{k} = toCellList(mapGet(ann, 'subsystem'));
                ann = mapDelete(ann, 'subsystem');
            end
            if mapHas(ann, 'references')
                model.rxnReferences{k} = collapseList(mapGet(ann, 'references'));
                ann = mapDelete(ann, 'references');
            end
            if mapHas(ann, 'notes')
                model.rxnNotes{k} = collapseList(mapGet(ann, 'notes'));
                ann = mapDelete(ann, 'notes');
            end
            if mapHas(ann, 'rxnFrom')
                model.rxnFrom{k} = collapseList(mapGet(ann, 'rxnFrom'));
                ann = mapDelete(ann, 'rxnFrom');
            end
            if mapHas(ann, 'deltaG')
                model.rxnDeltaG{k} = collapseList(mapGet(ann, 'deltaG'));
                ann = mapDelete(ann, 'deltaG');
            end
            model.rxnMiriams{k} = annotationToMiriam(ann);
        end
        %Top-level fields per the canonical schema. (Annotation rescue
        %above already covered the legacy-inside-annotation layout.)
        if isempty(model.eccodes{k}) && mapHas(r, 'eccodes')
            model.eccodes{k} = getField(r, 'eccodes', '');
        end
        if isempty(model.rxnReferences{k}) && mapHas(r, 'references')
            model.rxnReferences{k} = getField(r, 'references', '');
        end
        if (isempty(model.subSystems{k}) || (iscell(model.subSystems{k}) && isempty(model.subSystems{k}))) && mapHas(r, 'subsystem')
            sub = mapGet(r, 'subsystem');
            if ischar(sub) || isstring(sub)
                model.subSystems{k} = {char(sub)};
            elseif iscell(sub)
                model.subSystems{k} = sub(:);
            end
        end
        if isempty(model.rxnNotes{k}) && mapHas(r, 'notes')
            model.rxnNotes{k} = getField(r, 'notes', '');
        end
        if isempty(model.rxnFrom{k}) && mapHas(r, 'rxnFrom')
            model.rxnFrom{k} = getField(r, 'rxnFrom', '');
        end
        if isempty(model.rxnDeltaG{k}) && mapHas(r, 'deltaG')
            model.rxnDeltaG{k} = getField(r, 'deltaG', '');
        end
    end
end

%Genes.
genes = mapGet(doc, 'genes', {});
if iscell(genes) && size(genes, 2) ~= 2
    ng = numel(genes);
    model.genes          = repmat({''},ng,1);
    model.geneShortNames = repmat({''},ng,1);
    model.proteins       = repmat({''},ng,1);
    model.geneMiriams    = cell(ng,1);
    for k = 1:ng
        g = genes{k};
        if ~iscell(g) || size(g, 2) ~= 2, continue, end
        model.genes{k}          = getField(g,'id','');
        model.geneShortNames{k} = getField(g,'name','');
        model.proteins{k}       = getField(g,'protein','');
        ann = mapGet(g, 'annotation', cell(0,2));
        if iscell(ann) && size(ann, 2) == 2
            model.geneMiriams{k} = annotationToMiriam(ann);
        end
    end
end

%Gecko-light flag.
isGECKO = false;
if mapHas(doc, 'gecko_light')
    isGECKO = true;
    model.ec.geckoLight = isTruthy(mapGet(doc, 'gecko_light'));
end

%ec-rxns.
enzStoich = {};
ecRxns = mapGet(doc, 'ec-rxns', {});
if iscell(ecRxns) && size(ecRxns, 2) ~= 2 && ~isempty(ecRxns)
    isGECKO = true;
    if ~isfield(model,'ec') || ~isfield(model.ec,'geckoLight')
        model.ec.geckoLight = false;
    end
    ne = numel(ecRxns);
    %String fields pre-seeded with '' so any unset entries match the
    %char-empty convention the legacy pipeline produces (cell(N,1)
    %would have left them as the [] empty-double default).
    model.ec.rxns    = repmat({''},ne,1);
    model.ec.kcat    = cell(ne,1);
    model.ec.source  = repmat({''},ne,1);
    model.ec.notes   = repmat({''},ne,1);
    model.ec.eccodes = repmat({''},ne,1);
    for k = 1:ne
        e = ecRxns{k};
        if ~iscell(e) || size(e, 2) ~= 2, continue, end
        model.ec.rxns{k}   = getField(e,'id','');
        model.ec.kcat{k}   = getField(e,'kcat','');
        model.ec.source{k} = getField(e,'source','');
        model.ec.notes{k}  = getField(e,'notes','');
        if mapHas(e, 'eccodes')
            model.ec.eccodes{k} = joinList(mapGet(e, 'eccodes'), ';');
        end
        enzMap = mapGet(e, 'enzymes', cell(0,2));
        if iscell(enzMap) && size(enzMap, 2) == 2
            for s = 1:size(enzMap, 1)
                enzId = enzMap{s, 1};
                coeff = str2double(stringify(enzMap{s, 2}));
                enzStoich(end+1,1:3) = {k, enzId, coeff}; %#ok<AGROW>
            end
        end
    end
end

%ec-enzymes.
ecEnz = mapGet(doc, 'ec-enzymes', {});
if iscell(ecEnz) && size(ecEnz, 2) ~= 2 && ~isempty(ecEnz)
    isGECKO = true;
    if ~isfield(model,'ec') || ~isfield(model.ec,'geckoLight')
        model.ec.geckoLight = false;
    end
    nEnz = numel(ecEnz);
    model.ec.genes    = repmat({''},nEnz,1);
    model.ec.enzymes  = repmat({''},nEnz,1);
    model.ec.mw       = cell(nEnz,1);
    model.ec.sequence = repmat({''},nEnz,1);
    model.ec.concs    = cell(nEnz,1);
    for k = 1:nEnz
        e = ecEnz{k};
        if ~iscell(e) || size(e, 2) ~= 2, continue, end
        model.ec.genes{k}    = getField(e,'genes','');
        model.ec.enzymes{k}  = getField(e,'enzymes','');
        model.ec.mw{k}       = getField(e,'mw','');
        model.ec.sequence{k} = getField(e,'sequence','');
        model.ec.concs{k}    = getField(e,'concs','');
    end
end

%Common finalisation: compartment lookup, stoich matrix, type coercions,
%empty-or-fill defaults, rxnGeneMat. Shared with parseLegacy.
model = finaliseYAMLmodel(model, equations, enzStoich, isGECKO, verbose);
end

function out = getField(pairs, name, default)
%Lookup `name` in `pairs` (Nx2 cell from parseMapping) and stringify the
%value. Returns `default` if `name` is absent.
if mapHas(pairs, name)
    out = stringify(mapGet(pairs, name));
else
    out = default;
end
end

function out = stringify(v)
if iscell(v)
    if isempty(v)
        out = '';
    else
        out = char(v{1});
    end
elseif isstring(v)
    if numel(v) == 0
        out = '';
    else
        out = char(v(1));
    end
elseif isnumeric(v)
    if isnan(v)
        out = 'NaN';
    else
        out = sprintf('%.15g',v);
    end
elseif islogical(v)
    if v, out = 'true'; else, out = 'false'; end
else
    out = char(v);
end
end

function out = collapseList(v)
%Annotation values arrive as one-element lists in canonical YAML; collapse
%to a single string for RAVEN's scalar-string fields.
if iscell(v)
    parts = cellfun(@stringify,v,'UniformOutput',false);
    out = strjoin(parts,';');
elseif isstruct(v)
    %Shouldn't happen for these fields, but be permissive.
    out = '';
else
    out = stringify(v);
end
end

function out = toCellList(v)
if iscell(v)
    out = cellfun(@stringify,v,'UniformOutput',false);
elseif ischar(v) || isstring(v)
    out = {char(v)};
elseif isnumeric(v)
    out = {stringify(v)};
else
    out = {};
end
end

function out = joinList(v,sep)
out = strjoin(toCellList(v),sep);
end

function tf = isTruthy(v)
s = stringify(v);
tf = any(strcmpi(s,{'true','yes','1'}));
end

function miriam = annotationToMiriam(ann)
%Convert an `annotation:` block (Nx2 pairs of namespace -> values) into
%RAVEN's miriam struct ({name, value} parallel cell arrays).
miriam = [];
if ~iscell(ann) || size(ann, 2) ~= 2
    return
end
names  = {};
values = {};
for i = 1:size(ann, 1)
    vals = toCellList(ann{i, 2});
    if isempty(vals)
        continue
    end
    for j = 1:numel(vals)
        names{end+1,1}  = ann{i, 1}; %#ok<AGROW>
        values{end+1,1} = vals{j};   %#ok<AGROW>
    end
end
if isempty(names)
    miriam = [];
    return
end
miriam.name  = names;
miriam.value = values;
end

