Description of permuteModel
Home > manipulation > permuteModel.m
permuteModel
PURPOSE
permuteModel Change the order of the reactions or metabolites in a model.
SYNOPSIS
function newModel=permuteModel(model, indexes, type)
DESCRIPTION
 permuteModel  Change the order of the reactions or metabolites in a model.
 Parameters
 ----------
 model : struct
     a model structure.
 indexes : double
     a vector with the same length as the number of items in the model,
     which gives the new order of items.
 type : char
     'rxns' for reactions, 'mets' for metabolites, 'genes' for genes,
     'comps' for compartments.
 Returns
 -------
 newModel : struct
     an updated model structure.
 Examples
 --------
     newModel = permuteModel(model, indexes, type);
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
changeRxns changeRxns Modify the equations of reactions in a model.
sortIdentifiers sortIdentifiers Sort model identifiers alphabetically.
sortModel sortModel Sort a model based on metabolite names and compartments.
SOURCE CODE
function newModel=permuteModel(model, indexes, type)
% permuteModel  Change the order of the reactions or metabolites in a model.
%
% Parameters
% ----------
% model : struct
%     a model structure.
% indexes : double
%     a vector with the same length as the number of items in the model,
%     which gives the new order of items.
% type : char
%     'rxns' for reactions, 'mets' for metabolites, 'genes' for genes,
%     'comps' for compartments.
%
% Returns
% -------
% newModel : struct
%     an updated model structure.
%
% Examples
% --------
%     newModel = permuteModel(model, indexes, type);
newModel=model;
type=char(type);
switch type
    case 'rxns'
        if isfield(newModel,'rxns')
            newModel.rxns=newModel.rxns(indexes);
        end
        if isfield(newModel,'lb')
            newModel.lb=newModel.lb(indexes);
        end
        if isfield(newModel,'ub')
            newModel.ub=newModel.ub(indexes);
        end
        if isfield(newModel,'rev')
            newModel.rev=newModel.rev(indexes);
        end
        if isfield(newModel,'c')
            newModel.c=newModel.c(indexes);
        end
        if isfield(newModel,'S')
            newModel.S=newModel.S(:,indexes);
        end
        if isfield(newModel,'rxnNames')
            newModel.rxnNames=newModel.rxnNames(indexes);
        end
        if isfield(newModel,'rxnGeneMat')
            newModel.rxnGeneMat=newModel.rxnGeneMat(indexes,:);
        end
        if isfield(newModel,'grRules')
            newModel.grRules=newModel.grRules(indexes);
        end
        if isfield(newModel,'subSystems')
            newModel.subSystems=newModel.subSystems(indexes);
        end
        if isfield(newModel,'eccodes')
            newModel.eccodes=newModel.eccodes(indexes);
        end
        if isfield(newModel,'equations')
            newModel.equations=newModel.equations(indexes);
        end
        if isfield(newModel,'rxnMiriams')
            newModel.rxnMiriams=newModel.rxnMiriams(indexes);
        end
        if isfield(newModel,'rxnComps')
            newModel.rxnComps=newModel.rxnComps(indexes);
        end
        if isfield(newModel,'rxnFrom')
            newModel.rxnFrom=newModel.rxnFrom(indexes);
        end
        if isfield(newModel,'rxnScores')
            newModel.rxnScores=newModel.rxnScores(indexes);
        end
        if isfield(newModel,'rxnNotes')
            newModel.rxnNotes=newModel.rxnNotes(indexes);
        end
        if isfield(newModel,'rxnReferences')
            newModel.rxnReferences=newModel.rxnReferences(indexes);
        end
        if isfield(newModel,'rxnConfidenceScores')
            newModel.rxnConfidenceScores=newModel.rxnConfidenceScores(indexes);
        end
        if isfield(newModel,'rxnDeltaG')
            newModel.rxnDeltaG=newModel.rxnDeltaG(indexes);
        end
    case 'mets'
        if isfield(newModel,'mets')
            newModel.mets=newModel.mets(indexes);
        end
        if isfield(newModel,'metNames')
            newModel.metNames=newModel.metNames(indexes);
        end
        if isfield(newModel,'b')
            newModel.b=newModel.b(indexes,:);
        end
        if isfield(newModel,'metComps')
            newModel.metComps=newModel.metComps(indexes);
        end
        if isfield(newModel,'S')
            newModel.S=newModel.S(indexes,:);
        end
        if isfield(newModel,'unconstrained')
            newModel.unconstrained=newModel.unconstrained(indexes);
        end
        if isfield(newModel,'metMiriams')
            newModel.metMiriams=newModel.metMiriams(indexes,:);
        end
        if isfield(newModel,'inchis')
            newModel.inchis=newModel.inchis(indexes);
        end
        if isfield(newModel,'metSmiles')
            newModel.metSmiles=newModel.metSmiles(indexes);
        end
        if isfield(newModel,'metFormulas')
            newModel.metFormulas=newModel.metFormulas(indexes);
        end
        if isfield(newModel,'metFrom')
            newModel.metFrom=newModel.metFrom(indexes);
        end
        if isfield(newModel,'metCharges')
            newModel.metCharges=newModel.metCharges(indexes);
        end
        if isfield(newModel,'metDeltaG')
            newModel.metDeltaG=newModel.metDeltaG(indexes);
        end
    case 'genes'
        if isfield(newModel,'genes')
            newModel.genes=newModel.genes(indexes);
        end
        if isfield(newModel,'geneComps')
            newModel.geneComps=newModel.geneComps(indexes);
        end
        if isfield(newModel,'geneMiriams')
            newModel.geneMiriams=newModel.geneMiriams(indexes);
        end
        if isfield(newModel,'geneShortNames')
            newModel.geneShortNames=newModel.geneShortNames(indexes);
        end
        if isfield(newModel,'proteins')
            newModel.proteins=newModel.proteins(indexes);
        end
        if isfield(newModel,'rxnGeneMat')
            newModel.rxnGeneMat=newModel.rxnGeneMat(:,indexes);
        end
    case 'comps'
        if isfield(newModel,'comps')
            newModel.comps=newModel.comps(indexes);
        end
        if isfield(newModel,'compNames')
            newModel.compNames=newModel.compNames(indexes);
        end
        if isfield(newModel,'compOutside')
            newModel.compOutside=newModel.compOutside(indexes);
        end
        if isfield(newModel,'compMiriams')
            newModel.compMiriams=newModel.compMiriams(indexes);
        end
        [~,J]=sort(indexes); % The *index* of compartment is used in next fields
        if isfield(newModel,'metComps')
            [toreplace, bywhat] = ismember(newModel.metComps,1:length(J));
            newModel.metComps(toreplace) = J(bywhat(toreplace));
        end
        if isfield(model,'rxnComps')
            [toreplace, bywhat] = ismember(model.rxnComps,1:length(J));
            model.rxnComps(toreplace) = J(bywhat(toreplace));
        end
        if isfield(model,'geneComps')
            [toreplace, bywhat] = ismember(model.geneComps,1:length(J));
            model.geneComps(toreplace) = J(bywhat(toreplace));
        end
end
end