function [model,KOModel]=getModelFromKEGG(varargin)
% getModelFromKEGG  Load the pre-built global KEGG model.
%
% Loads the pre-built global KEGG reaction/gene model from keggModel.mat.
% The artefact is generated by the raven-toolbox Python package and
% distributed as a raven-data release asset.
%
% Name-Value Arguments
% --------------------
% keepSpontaneous : logical
%     include reactions labeled as "spontaneous" (default true).
% keepUndefinedStoich : logical
%     include reactions in the form n A <=> n+1 A (default true).
% keepIncomplete : logical
%     include reactions labelled as "incomplete", "erroneous" or "unclear"
%     (default true).
% keepGeneral : logical
%     include reactions labelled as "general reaction" (default false).
%
% Returns
% -------
% model : struct
%     a model structure with all reactions and the metabolites used in them.
% KOModel : struct
%     a model structure representing KEGG Orthology ids and their associated
%     genes. KO ids are stored as reactions.
%
% Notes
% -----
% The model output can be used as a template for fillGaps. In that case,
% remove the genes and rxnGeneMat fields before parsing:
%     model = rmfield(model, 'genes'), etc.
%
% See also
% --------
% getKEGGModelForOrganism, getPhylDist, fillGaps

ravenPath=findRAVENroot();

p=parseRAVENargs(varargin, {'keepSpontaneous',true; 'keepUndefinedStoich',true; ...
    'keepIncomplete',true; 'keepGeneral',false});
keepSpontaneous=p.keepSpontaneous;
keepUndefinedStoich=p.keepUndefinedStoich;
keepIncomplete=p.keepIncomplete;
keepGeneral=p.keepGeneral;

modelFile=fullfile(ravenPath,'reconstruction','kegg','keggModel.mat');
if ~exist(modelFile,'file')
    error('getModelFromKEGG:noModel', ...
        ['keggModel.mat not found at ' strrep(modelFile,'\','/') '.\n' ...
        'Generate it with the raven-toolbox Python package or download it ' ...
        'via downloadRavenBinaries.']);
end
fprintf(['Importing the global KEGG model from ' strrep(modelFile,'\','/') '... ']);
load(modelFile);
fprintf('COMPLETE\n');

if keepSpontaneous==false
    model=removeReactions(model,intersect(isSpontaneous,model.rxns),true,true);
end
if keepUndefinedStoich==false
    model=removeReactions(model,intersect(isUndefinedStoich,model.rxns),true,true);
end
if keepIncomplete==false
    model=removeReactions(model,intersect(isIncomplete,model.rxns),true,true);
end
if keepGeneral==false
    model=removeReactions(model,intersect(isGeneral,model.rxns),true,true);
end
end
