Description of tutorial3
Home > tutorial > tutorial3.m
tutorial3
PURPOSE
This contains the code necessary for running Exercises 3. It is assumed
SYNOPSIS
This is a script file.
DESCRIPTION
This contains the code necessary for running Exercises 3. It is assumed
that you are somewhat familiar with linear programming.
CROSS-REFERENCE INFORMATION
This function calls:
canConsume canConsume
checkProduction checkProduction
fillGaps fillGaps
gapReport gapReport
printFluxes printFluxes
simplifyModel simplifyModel
importExcelModel importExcelModel
solveLP solveLP
This function is called by:
SOURCE CODE
%This contains the code necessary for running Exercises 3. It is assumed
%that you are somewhat familiar with linear programming.
%Load the model
model=importExcelModel('smallYeastBad.xlsx');
model.b=[model.b inf(numel(model.b),1)];
sol=solveLP(model,1);
printFluxes(model,sol.x,false,10^-5,[],'%rxnID (%rxnName):\n\t%eqn\n\t%flux\n');
I=canConsume(model);
model.mets(I)
gapReport(model,{refModel});
model=importExcelModel('smallYeastBad2.xlsx');
[reducedModel, deletedReactions, deletedMetabolites]=simplifyModel(model,false,false,false,true);
deletedReactions
deletedMetabolites
[notProducedMets, crap, neededForProductionMat,minToConnect]=checkProduction(model,true,model.comps,false);
minToConnect
refModel=importExcelModel('smallYeast.xlsx');
[newConnected cannotConnect addedRxns newModel]=fillGaps(model,{refModel},false);
addedRxns
newConnected
cannotConnect