Description of tutorial1_solutions
Home > tutorial > tutorial1_solutions.m
tutorial1_solutions
PURPOSE
This is the solution to tutorial 1. The file small.xlsx contains all the
SYNOPSIS
This is a script file.
DESCRIPTION
This is the solution to tutorial 1. The file small.xlsx contains all the
necessary modifications to solve for ATP production in glycolysis.
CROSS-REFERENCE INFORMATION
This function calls:
printFluxes printFluxes
importExcelModel importExcelModel
solveLP solveLP
This function is called by:
SOURCE CODE
%This is the solution to tutorial 1. The file small.xlsx contains all the
%necessary modifications to solve for ATP production in glycolysis.
%This loads the Excel model and converts it into a RAVEN model structure
smallModel=importExcelModel('small.xlsx')
%This solves the problem. If it looks like:
%sol=
%   f: []
%...
%then the problem is not solvable. Be sure that you have added uptake and
%excretion of all necessary stuff.
sol=solveLP(smallModel)
%Print the resulting exchange fluxes
printFluxes(smallModel,sol.x,true);
%Print all fluxes
printFluxes(smallModel,sol.x,false,10^-5,[],'%rxnID (%rxnName):\n\t%eqn\n\t%flux\n');