Description of loadWorkbook
Home > io > loadWorkbook.m
loadWorkbook
PURPOSE
loadWorkbook Load an Excel file into a Workbook object.
SYNOPSIS
function workbook=loadWorkbook(fileName,createEmpty)
DESCRIPTION
 loadWorkbook  Load an Excel file into a Workbook object.
 Loads an Excel file into a Workbook object using the Java library Apache
 POI.
 Parameters
 ----------
 fileName : char
     name of the Excel file. If it doesn't exist it will be created.
 createEmpty : logical, optional
     true if an empty workbook should be created if the file didn't exist
     (default false).
 Returns
 -------
 workbook : Workbook
     Workbook object representing the Excel file.
 Examples
 --------
     workbook = loadWorkbook(fileName, createEmpty);
CROSS-REFERENCE INFORMATION
This function calls:
addJavaPaths addJavaPaths Add the Apache POI classes to the static Java paths.
getFullPath getFullPath Get the absolute canonical path of a file or folder.
This function is called by:
exportToExcelFormat exportToExcelFormat Export a model to the Microsoft Excel model format.
importExcelModel importExcelModel Import a constraint-based model from an Excel file.
SOURCE CODE
function workbook=loadWorkbook(fileName,createEmpty)
% loadWorkbook  Load an Excel file into a Workbook object.
%
% Loads an Excel file into a Workbook object using the Java library Apache
% POI.
%
% Parameters
% ----------
% fileName : char
%     name of the Excel file. If it doesn't exist it will be created.
% createEmpty : logical, optional
%     true if an empty workbook should be created if the file didn't exist
%     (default false).
%
% Returns
% -------
% workbook : Workbook
%     Workbook object representing the Excel file.
%
% Examples
% --------
%     workbook = loadWorkbook(fileName, createEmpty);
if nargin<2
    createEmpty=false;
end
%Check if the user has MATLAB Text Analytics Toolbox installed, as it comes
%with its own conflicting version of the required Apache POI files
if exist('vaderSentimentScores.m')== 2
    error(['MATLAB Text Analytics Toolbox found. This should be uninstalled ' ...
           'if you want to read/write Excel files. See RAVEN GitHub Issues '...
           'page for instructions.'])
end
%Adds the required classes to the static Java path if not already added
addJavaPaths();
%Import required classes from Apache POI
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.ss.util.*;
import java.io.FileInputStream;
import org.apache.poi.hssf.usermodel.*;
import org.apache.poi.xssf.usermodel.*;
%Check if the file exists
if ~isfile(fileName)
    if createEmpty==false
        EM='The Excel file could not be found';
        dispEM(EM);
    else
        %Create an empty workbook
        [~,~,I]=fileparts(fileName);
        if strcmpi(I,'.xls')
            workbook=HSSFWorkbook();
        else
            if strcmpi(I,'.xlsx')
                workbook=XSSFWorkbook();
            else
                EM='The file name must end in .xls or .xlsx';
                dispEM(EM);
            end
        end
    end
else
    %Opens the workbook. The input stream is needed since it will otherwise
    %keep the file open
    is=FileInputStream(getFullPath(fileName));
    workbook=WorkbookFactory.create(is);
    is.close();
end
end