function [solutions, goodRxns]=randomSampling(model,varargin)
% randomSampling  Perform random sampling of the solution space.
%
% Performs random sampling of the solution space, as described in Bordel et
% al. (2010) PLoS Comput Biol (doi:10.1371/journal.pcbi.1000859).
%
% Parameters
% ----------
% model : struct
%     a model structure.
%
% Name-Value Arguments
% --------------------
% nSamples : double
%     the number of solutions to return (default 1000).
% replaceBoundsWithInf : logical
%     replace the largest upper bounds with Inf and the smallest lower
%     bounds with -Inf. This is needed in order to get solutions without
%     loops if your model has, for example, 1000/-1000 as arbitrarily large
%     bounds. If your model only has "biologically relevant" bounds, then
%     set this to false (default true).
% supressErrors : logical
%     the program will halt if it has problems finding non-zero solutions
%     which are not involved in loops. This could be because the constraints
%     on the model are too relaxed (such as unlimited glucose uptake) or too
%     strict (such as too many and too narrow constraints) (default false).
% runParallel : logical
%     speed up calculations by parallel processing. Requires the MATLAB
%     Parallel Computing Toolbox. If this is not installed, the calculations
%     will not be parallelized, regardless of what is indicated as
%     runParallel (default true).
% goodRxns : double
%     vector of indexes of those reactions that are not involved in loops
%     and can be used as random objective functions, as generated by a
%     previous run of randomSampling on the same model (default empty).
% minFlux : logical
%     determines if a second optimization should be performed for each
%     random sample, to minimize the number of fluxes and thereby prevent
%     loops. Typically, loops are averaged out when a large number of
%     samples are taken, but this is not always the case (default false).
% nObjectives : double
%     number of reactions included in the random objective function per
%     sample iteration (default 2).
% seed : double
%     random seed for reproducibility. If empty, the current MATLAB random
%     state is used (default empty).
%
% Returns
% -------
% solutions : double
%     matrix with the solutions.
% goodRxns : double
%     vector of indexes of those reactions that are not involved in loops or
%     always carry zero flux and can be used as random objective functions.
%
% Notes
% -----
% The solutions are generated by maximizing (with random weights) for a
% random set of nObjectives reactions (default 2). For reversible reactions
% it randomly chooses between maximizing and minimizing.
%
% If the model is a GECKO v3+ ecModel, then usage_prot reactions are not
% selected for sampling, instead focusing on sampling from the metabolic
% aspects that form the solution space.
%
% Examples
% --------
%     solutions = randomSampling(model, nSamples, replaceBoundsWithInf, ...
%                     supressErrors, runParallel, goodRxns, minFlux);

p=parseRAVENargs(varargin, {'nSamples',[]; 'replaceBoundsWithInf',[]; 'supressErrors',[]; 'runParallel',[]; 'goodRxns',[]; 'minFlux',[]; 'nObjectives',[]; 'seed',[]});
nSamples=p.nSamples;
replaceBoundsWithInf=p.replaceBoundsWithInf;
supressErrors=p.supressErrors;
runParallel=p.runParallel;
goodRxns=p.goodRxns;
minFlux=p.minFlux;
nObjectives=p.nObjectives;
seed=p.seed;
if isempty(nSamples)
    nSamples=1000;
end
if isempty(replaceBoundsWithInf)
    replaceBoundsWithInf=true;
end
if isempty(supressErrors)
    supressErrors=false;
end
if isempty(runParallel)
    runParallel=true;
end
if isempty(minFlux)
    minFlux=false;
end
if isempty(nObjectives)
    nObjectives=2;
end

nW = parallelWorkersRAVEN(runParallel);

nObjRxns=nObjectives;

%Simplify the model to speed stuff up a little. Keep original mapping
originalRxns=model.rxns;
model=simplifyModel(model,false,false,true,true);
[~, simpToOrig] = ismember(model.rxns, originalRxns);

%goodRxns is part of the public API and stored as original-model indices.
%Convert to simplified-model indices for use in the detection and sampling
%loops below, dropping any reactions that were removed by simplification.
if ~isempty(goodRxns)
    [tf, simpIdx] = ismember(originalRxns(goodRxns), model.rxns);
    goodRxns = double(simpIdx(tf));
end

%Check that the model is feasible given the constraints
[sol,~]=solveLP(model);
if isempty(sol.x)
    EM='The model has no feasible solution, likely due to incompatible constraints';
    dispEM(EM);
elseif sol.f==0
    warning('The model objective function cannot reach a non-zero value. This might be intended, so randomSampling will continue, but this could indicate problems with your model')
end

nRxns = numel(model.rxns);
%Reactions which can be involved in loops should not be optimized for.
%Check which reactions reach an arbitrary high upper bound. This is done
%on the original bounded model so that loop detection is meaningful
%(Inf-bounded reactions would always reach the threshold).
if isempty(goodRxns)
    [minF, maxF] = getAllowedBounds(model, 'runParallel', runParallel);
    goodRxns = true(nRxns, 1);
    % Reactions that reach ±1000 are involved in loops
    goodRxns(maxF > 999 | minF < -999) = false;
    % Reactions that cannot carry any non-zero flux
    goodRxns(~(maxF > 0 | minF < 0)) = false;
    % In ecModels do not sample from usage_prot reactions
    if isfield(model,'ec')
        goodRxns(startsWith(model.rxns,'usage_prot_')) = false;
    end
    goodRxns = find(goodRxns);
end

%Change the bounds to +/- Inf to prevent loops in the sampled solutions.
%Applied after goodRxns detection so that loop-detection uses original bounds.
if replaceBoundsWithInf==true
    model.ub(model.ub==max(model.ub))=Inf;
    if min(model.lb)<0 % Only negative lower bounds should be set to -Inf
        model.lb(model.lb==min(model.lb))=-Inf;
    end
end

%Seed the RNG here so that only the sampling loop is affected, not the
%model simplification or goodRxns detection above.
if ~isempty(seed)
    rng(seed);
end

%Reserve space for a solution matrix
sols = zeros(numel(model.rxns),nSamples);
sols = num2cell(sols,1);

%Main loop
if nSamples > 0

    PB = progressReport(nSamples,'Performing random sampling');
    parfor (i = 1:nSamples, nW)
        badSolutions = 1;
        tmpModel = model;
        while lt(0,badSolutions)
            rxns = goodRxns(randperm(numel(goodRxns), nObjRxns));
            tmpModel.c = zeros(numel(tmpModel.rxns),1);

            multipliers = 2*randi(2,nObjRxns,1)-3;  % random draws from {-1, 1}
            multipliers(tmpModel.ub(rxns)<0) = 1;

            tmpModel.c(rxns) = rand(nObjRxns,1).*multipliers;

            if true(minFlux)
                sol=solveLP(tmpModel,1);
            else
                sol=solveLP(tmpModel,0);
            end
            if any(sol.x) && abs(sol.f)>10^-8
                sols{i} = sol.x;
                badSolutions = 0;
            else
                badSolutions = badSolutions+1;
                %If it only finds bad solutions then throw an error.
                if badSolutions == 100 && supressErrors==false
                    error('The program is having problems finding non-zero solutions (ignoring reactions that might be involved in loops). Review the constraints on your model. Set supressErrors to true to ignore this error');
                end
            end
        end
        count(PB);
    end

    %Map to original model
    sols = cell2mat(sols);
    solutions=zeros(numel(originalRxns),nSamples);
    solutions(simpToOrig,:)=sols;
else
    solutions=[];
end
%Return goodRxns as original-model indices so callers can pass them back
%safely across separate calls (which each re-simplify the model internally).
goodRxns = double(simpToOrig(goodRxns));
end
