function solutions = sampleACHR(model, nSamples, thinning, warmup, seed)
% sampleACHR  Artificially Centered Hit-and-Run flux sampling.
%
% Draws nSamples flux vectors from the flux polytope {v : S*v = 0, lb <= v <= ub}
% using ACHR (Kaufman & Smith 1998): from the current point, step towards a
% randomly chosen warmup vertex through the running centre of all points so far,
% sampling uniformly along the feasible chord. No rounding is performed, so on
% strongly elongated polytopes (e.g. enzyme-constrained models) mixing is slower
% than sampleCHRR; prefer CHRR there.
%
% Because every search direction is a difference of feasible points (which all
% satisfy S*v = 0), each step stays exactly on the steady-state manifold.
%
% Parameters
% ----------
% model : struct
%     a RAVEN model structure.
% nSamples : double
%     number of flux vectors to return (default 1000).
% thinning : double
%     Markov-chain steps between recorded samples (default 100).
% warmup : double
%     nPoints-by-nRxns warmup vertices (default: generated by sampleWarmupPoints).
% seed : double
%     random seed for reproducibility (default: current RNG state).
%
% Returns
% -------
% solutions : double
%     nRxns-by-nSamples matrix of sampled flux distributions.
%
% See also
% --------
% sampleFluxSpace, sampleCHRR, sampleWarmupPoints, randomSampling

if nargin < 2 || isempty(nSamples); nSamples = 1000; end
if nargin < 3 || isempty(thinning); thinning = 100;  end
if nargin < 4 || isempty(warmup);   warmup = sampleWarmupPoints(model); end
if nargin < 5;                      seed = [];        end
if ~isempty(seed)
    rng(seed);
end

nRxns = numel(model.rxns);
lb = model.lb(:);
ub = model.ub(:);
nW = size(warmup, 1);

center = mean(warmup, 1)';             % nRxns-by-1
prev = center;
nTotal = 0;
dirTol = 1e-12;

solutions = zeros(nRxns, nSamples);
rec = 0;
nSteps = thinning*nSamples;

for stepno = 1:nSteps
    pidx = randi(nW);
    delta = warmup(pidx, :)' - center;

    posD = delta > dirTol;
    negD = delta < -dirTol;
    ubp = ub - prev;
    lbp = lb - prev;
    % alpha range keeping lb <= prev + alpha*delta <= ub
    upperLims = [ubp(posD)./delta(posD); lbp(negD)./delta(negD)];
    lowerLims = [lbp(posD)./delta(posD); ubp(negD)./delta(negD)];
    if isempty(upperLims); tHi = 0; else; tHi = min(upperLims); end
    if isempty(lowerLims); tLo = 0; else; tLo = max(lowerLims); end

    if tHi > tLo
        alpha = tLo + rand*(tHi - tLo);
        prev = prev + alpha*delta;
    end

    % Running centre (quasi-Markovian ACHR: centre converges and steadies).
    center = (nTotal*center + prev) / (nTotal + 1);
    nTotal = nTotal + 1;

    if mod(stepno, thinning) == 0
        rec = rec + 1;
        solutions(:, rec) = prev;
    end
end
end
