Description of convertCharArray
Home > core > convertCharArray.m
convertCharArray
PURPOSE
convertCharArray
SYNOPSIS
function inputConverted = convertCharArray(funcInput)
DESCRIPTION
convertCharArray
   Converts input to make sure it is a cell array of character vectors.
   String arrays are transformed into character vectors, and if only one
   character vector is given. Output is always a cell array, also if only
   one character vector is given as input.
   Input:
   funcInput          function input that should be checked
   Output:
   inputConverted      cell array of character vectors
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
addExchangeRxns addExchangeRxns
addGenesRaven addGenesRaven
addMets addMets
addRxns addRxns
addRxnsGenesMets addRxnsGenesMets
addTransport addTransport
buildEquation buildEquation
canConsume canConsume
canProduce canProduce
changeGrRules changeGrRules
changeRxns changeRxns
checkProduction checkProduction
constructEquations constructEquations
constructS constructS
consumeSomething consumeSomething
convertToIrrev convertToIrrev
copyToComps copyToComps
dispEM dispEM
fitParameters fitParameters
followChanged followChanged
getAllRxnsFromGenes getAllRxnsFromGenes
getAllowedBounds getAllowedBounds
getElementalBalance getElementalBalance
getEssentialRxns getEssentialRxns
getIndexes getIndexes
getMinNrFluxes getMinNrFluxes
getModelFromHomology getModelFromHomology
haveFlux haveFlux
makeSomething makeSomething
printFluxes printFluxes
printModel printModel
removeBadRxns removeBadRxns
removeGenes removeGenes
removeMets removeMets
removeReactions removeReactions
reporterMetabolites reporterMetabolites
setExchangeBounds setExchangeBounds
setParam setParam
simplifyModel simplifyModel
SOURCE CODE
function inputConverted = convertCharArray(funcInput)
%convertCharArray
%   Converts input to make sure it is a cell array of character vectors.
%   String arrays are transformed into character vectors, and if only one
%   character vector is given. Output is always a cell array, also if only
%   one character vector is given as input.
%
%   Input:
%   funcInput          function input that should be checked
%
%   Output:
%   inputConverted      cell array of character vectors
%
if ~isempty(funcInput)
    if ischar(funcInput) || isstring(funcInput)
        inputConverted = {char(funcInput)};
    elseif ~iscell(funcInput) && ~(all(cellfun(@ischar, funcInput)) || all(cellfun(@isstring, funcInput)))
        error([inputname(1) ' should be a (cell array of) character vector(s)'])
    else
        inputConverted = cellstr(funcInput);
    end
else
    inputConverted=[];
end
end