Description of dispEM
Home > core > dispEM.m
dispEM
PURPOSE
dispEM
SYNOPSIS
function dispEM(string,throwErrors,toList,trimWarnings)
DESCRIPTION
 dispEM
   Helper function to print warning/errors
   string          the warning/error to show. "WARNING: " is appended automatically
                   if a warning
   throwErrors     true if the function should throw an error (opt, default true)
   toList          a cell array of items to list. If supplied, then the
                   string will be printed followed by each element in
                   toList. If it is supplied but empty then nothing is
                   printed (opt, default {})
   trimWarnings    true if only a maximal of 10 items should be displayed in
                   a given error/warning (opt, default true)
   Usage: dispEM(string,throwErrors,toList,trimWarnings)
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
addGenesRaven addGenesRaven
addMets addMets
addRxns addRxns
addRxnsGenesMets addRxnsGenesMets
addTransport addTransport
analyzeSampling analyzeSampling
buildEquation buildEquation
changeRxns changeRxns
checkModelStruct checkModelStruct
checkRxn checkRxn
checkTasks checkTasks
compareMultipleModels compareMultipleModels
compareRxnsGenesMetsComps compareRxnsGenesMetsComps
constructS constructS
consumeSomething consumeSomething
contractModel contractModel
expandModel expandModel
fillGaps fillGaps
findGeneDeletions findGeneDeletions
fitParameters fitParameters
fitTasks fitTasks
getElementalBalance getElementalBalance
getEssentialRxns getEssentialRxns
getExpressionStructure getExpressionStructure
getFluxZ getFluxZ
getMetsInComp getMetsInComp
getMinNrFluxes getMinNrFluxes
getModelFromHomology getModelFromHomology
getRxnsInComp getRxnsInComp
guessComposition guessComposition
makeSomething makeSomething
mapCompartments mapCompartments
mergeCompartments mergeCompartments
mergeModels mergeModels
parseTaskList parseTaskList
predictLocalization predictLocalization
printFluxes printFluxes
randomSampling randomSampling
removeBadRxns removeBadRxns
removeMets removeMets
replaceMets replaceMets
reporterMetabolites reporterMetabolites
setParam setParam
simplifyModel simplifyModel
sortModel sortModel
standardizeGrRules standardizeGrRules
SOURCE CODE
function dispEM(string,throwErrors,toList,trimWarnings)
% dispEM
%   Helper function to print warning/errors
%
%   string          the warning/error to show. "WARNING: " is appended automatically
%                   if a warning
%   throwErrors     true if the function should throw an error (opt, default true)
%   toList          a cell array of items to list. If supplied, then the
%                   string will be printed followed by each element in
%                   toList. If it is supplied but empty then nothing is
%                   printed (opt, default {})
%   trimWarnings    true if only a maximal of 10 items should be displayed in
%                   a given error/warning (opt, default true)
%
%   Usage: dispEM(string,throwErrors,toList,trimWarnings)
if nargin<2
    throwErrors=true;
end
if nargin<3
    toList=[];
elseif isempty(toList)
    return;
elseif ~iscell(toList)
    toList={toList};
end
if nargin<4
    trimWarnings=true;
end
if numel(toList)>10 && trimWarnings==true
    toList{10}=['...and ' num2str(numel(toList)-9) ' more'];
    toList(11:end)=[];
end
if throwErrors==false
    errorText=['WARNING: ' string '\n'];
else
    errorText=[string '\n'];
end
if ~isempty(toList)
    for i=1:numel(toList)
        errorText=[errorText '\t' toList{i} '\n'];
    end
end
if throwErrors==false
    %Escape special characters, required for fprintf
    errorText=regexprep(errorText,'(\\|\%|'')(\\n)$','\\$0');
    fprintf([errorText '\n']);
else
    throw(MException('',errorText));
end
end