function modelFields = legacyYAMLmodelFields()
% legacyYAMLmodelFields
%   The Nx2 (fieldName, defaultValue) schema both readYAMLmodel paths
%   use to seed an empty RAVEN model struct. Some entries start as
%   cell arrays of strings; finaliseYAMLmodel converts the relevant
%   ones to numeric arrays at the end (marked below).
modelFields =   {'id',char();...
               'name',char();...
        'description',char();...
            'version',char();...
               'date',char();...
         'annotation',struct();...
               'rxns',{};...
           'rxnNames',{};...
               'mets',{};...
           'metNames',{};...
                  'S',sparse([]);...
                 'lb',{};... %Changed to double in the end.
                 'ub',{};... %Changed to double in the end.
                'rev',{};... %Changed to double in the end.
                  'c',[];...
                  'b',cell(0,0);... %Changed to double in the end.
              'genes',cell(0,0);...
            'grRules',cell(0,0);...
         'rxnGeneMat',sparse([]);...
           'rxnComps',cell(0,0);... %Changed to double in the end.
         'subSystems',cell(0,0);...
            'eccodes',cell(0,0);...
         'rxnMiriams',cell(0,0);...
          'rxnDeltaG',{};... %Changed to double in the end.
           'rxnNotes',cell(0,0);...
      'rxnReferences',cell(0,0);...
'rxnConfidenceScores',cell(0,0);...
           'metComps',cell(0,0);... %Changed to double in the end.
             'inchis',cell(0,0);...
          'metSmiles',cell(0,0);...
        'metFormulas',cell(0,0);...
         'metMiriams',cell(0,0);...
          'metDeltaG',{};... %Changed to double in the end.
         'metCharges',cell(0,0);... %Changed to double in the end.
           'metNotes',cell(0,0);...
              'comps',cell(0,0);...
          'compNames',cell(0,0);...
        'compOutside',cell(0,0);...
          'geneComps',cell(0,0);... %Changed to double in the end.
        'geneMiriams',cell(0,0);...
     'geneShortNames',cell(0,0);...
       'proteins',cell(0,0);...
      'unconstrained',cell(0,0);... %Changed to double in the end.
            'metFrom',cell(0,0);...
            'rxnFrom',cell(0,0)};
end
